/* config.h. Generated by CMake for Player. */

/* Install prefix */
#define PLAYER_INSTALL_PREFIX "/opt/local"

/* enable TCP_NODELAY */
/* #undef ENABLE_TCP_NODELAY */

#define HAVE_GETADDRINFO 1
/* #undef HAVE_JPEG */
#define HAVE_Z 1
/* #undef HAVE_LINUX_JOYSTICK_H */
#define HAVE_STRINGS_H 1
#define HAVE_SYS_FILIO_H 1
/* #undef HAVE_IEEEFP_H */
/* #undef WORDS_BIGENDIAN */
/* #undef HAVE_SETDLLDIRECTORY */

